# Uebersetzungen fuer das Panel: deutscher Text -> Englisch
# Fehlt ein Eintrag, wird einfach der deutsche Text angezeigt.

function C([int]$codepoint) { [char]::ConvertFromUtf32($codepoint) }

$texts = @{
    # Navigation
    'Dashboard' = 'Dashboard'
    'Chatbox' = 'Chatbox'
    'Status' = 'Status'
    'Statistik' = 'Statistics'
    'Einstellungen' = 'Settings'
    'Erweitert' = 'Advanced'
    'Was gerade läuft und was über deinem Kopf steht' = 'What is playing and what shows above your head'
    'Was in der Chatbox steht und wie es aussieht' = 'What shows in the chatbox and how it looks'
    'Aussehen und Aufbau der Chatbox' = 'Look and layout of the chatbox'
    'Live-Songtexte, Karaoke und Übersetzung' = 'Live lyrics, karaoke and translation'
    'Uhrzeit, AFK, VRChat-Infos und eigene Texte' = 'Clock, AFK, VRChat info and custom texts'
    'Deine meistgehörten Songs und Künstler' = 'Your most played songs and artists'
    'Design, Verhalten und Programm' = 'Theme, behavior and program'
    'Verbindung, Lyrics-Timing, Tastenkürzel und Fehler-Log' = 'Connection, lyrics timing, hotkeys and error log'

    # Seitenleiste / Kopf
    'für VRChat' = 'for VRChat'
    'MENÜ' = 'MENU'
    'VRChat verbunden' = 'VRChat connected'
    'VRChat nicht gestartet' = 'VRChat not running'
    'OSC in VRChat ist aus' = 'OSC is off in VRChat'
    'Action Menu > Options > OSC > Enabled' = 'Action Menu > Options > OSC > Enabled'
    'Du sprichst - Chatbox pausiert' = 'You are talking - chatbox paused'
    'Spotify spielt nichts' = 'Nothing playing on Spotify'
    'Chatbox AN' = 'Chatbox ON'
    'Chatbox AUS' = 'Chatbox OFF'
    'Pausiert bis' = 'Paused until'

    # Dashboard
    'JETZT LÄUFT' = 'NOW PLAYING'
    'Klicken zum Spulen' = 'Click to seek'
    'Popup-Position' = 'Popup position'
    'Popup-Dauer' = 'Popup duration'
    'Chatbox-Profile' = 'Chatbox profiles'
    'Profil' = 'Profile'
    'Eigen' = 'Custom'
    'Schnell zwischen typischen Chatbox-Stilen wechseln' = 'Quickly switch between common chatbox styles'
    'Ein Profil stellt mehrere Anzeigeoptionen gemeinsam ein. Du kannst danach jede Einstellung weiter anpassen.' = 'A profile applies several display options together. You can still adjust each setting afterward.'
    'Clean' = 'Clean'
    'Lyrics' = 'Lyrics'
    'Minimal' = 'Minimal'
    'Start & Verlauf' = 'Startup & history'
    'Songwechsel-Popup' = 'Song change popup'
    'Daten' = 'Data'
    'Hilfe & Diagnose' = 'Help & diagnostics'
    'Nur bei Verbindungsproblemen relevant.' = 'Useful only when troubleshooting connection issues.'
    'Animationen reduzieren' = 'Reduce motion'
    'Schaltet Bewegungen und weiche Übergänge weitgehend ab' = 'Turns off most movement and soft transitions'
    'Cover im Popup-Hintergrund' = 'Cover art in popup background'
    'Albumcover weichgezeichnet hinter der Songkarte anzeigen' = 'Show a blurred album cover behind the song card'
    'Desktop-Popup' = 'Desktop popup'
    'In-VR-Benachrichtigung' = 'In-VR notification'
    'Songkarte auf deinem Bildschirm anzeigen' = 'Show the song card on your screen'
    'Songwechsel über XSOverlay in VR anzeigen, falls installiert' = 'Show song changes in VR through XSOverlay, if installed'
    'Dezentes Popup auf dem Desktop und in VR über XSOverlay' = 'Subtle desktop popup and in-VR XSOverlay notice'
    'Wo das Song-Popup auf dem Bildschirm erscheint' = 'Where the song popup appears on screen'
    'Wie lange das Popup sichtbar bleibt' = 'How long the popup stays visible'
    'Unten rechts' = 'Bottom right'
    'Unten links' = 'Bottom left'
    'Oben rechts' = 'Top right'
    'Oben links' = 'Top left'
    'Klicken zum Dashboard' = 'Click to open dashboard'
    'Zufallswiedergabe' = 'Shuffle'
    'Wiederholen' = 'Repeat'
    'VRChat-Welt' = 'VRChat world'
    'Heute gehört' = 'Listened today'
    'Songs (Sitzung)' = 'Songs (session)'
    'aus' = 'off'
    'Gefunden' = 'Found'
    'Suche Lyrics...' = 'Searching lyrics...'
    'Keine Lyrics gefunden' = 'No lyrics found'
    'Keine Verbindung - neuer Versuch gleich' = 'No connection - retrying shortly'
    'Eigene Lyrics' = 'Custom lyrics'
    'VORSCHAU' = 'PREVIEW'
    'SO STEHT ES ÜBER DEINEM KOPF' = 'THIS SHOWS ABOVE YOUR HEAD'
    'Zeichen' = 'characters'
    'Chatbox ist aus' = 'Chatbox is off'
    'Chatbox ist pausiert' = 'Chatbox is paused'
    '(nichts zu zeigen)' = '(nothing to show)'
    'Schnell-Schalter' = 'Quick switches'
    'Was über deinem Kopf steht, mit einem Klick' = 'What shows above your head, one click away'
    'Songtitel' = 'Song title'
    'Album' = 'Album'
    'Was angezeigt wird' = 'What is shown'
    'Jeden Teil der Chatbox einzeln an- und ausschalten' = 'Turn each part of the chatbox on or off'
    'Weitere Infos wie AFK oder die VRChat-Welt findest du unter Status.' = 'More info like AFK or the VRChat world is under Status.'
    'Wann die Chatbox gesendet wird' = 'When the chatbox is sent'
    'Übersetzung' = 'Translation'
    'Fortschrittsbalken' = 'Progress bar'
    'Balken' = 'Progress bar'
    'Ohne Hintergrund' = 'No background'
    'Uhrzeit' = 'Clock'
    'AFK' = 'AFK'
    'Pause' = 'Pause'
    'Chatbox kurz ausblenden, sie kommt danach von selbst zurück' = 'Hide the chatbox for a while, it comes back by itself'
    'Weiter' = 'Resume'
    'Chatbox läuft wieder' = 'Chatbox is back on'

    # Chatbox
    'Grundlagen' = 'Basics'
    'Wie und wann die Chatbox gesendet wird' = 'How and when the chatbox is sent'
    'Text schwebt ohne dunklen Kasten' = 'Text floats without the dark box'
    'Kompakt' = 'Compact'
    'Alles in einer einzigen Zeile' = 'Everything in a single line'
    'Bei Pause ausblenden' = 'Hide when paused'
    'Song verschwindet, wenn Spotify pausiert' = 'Song disappears when Spotify is paused'
    'Song nur kurz zeigen' = 'Show song briefly'
    'Nur 15 Sekunden nach einem Songwechsel' = 'Only for 15 seconds after a song change'
    'Aufräumen' = 'Clean up'
    'Farben vom Song übernehmen' = 'Use colors from the song'
    'Akzentfarbe passt sich dem Albumcover an' = 'Accent color adapts to the album cover'
    'Wird genutzt, wenn ein Song kein farbiges Cover hat' = 'Used when a song has no colorful cover'
    'Schnell pausieren' = 'Quick pause'
    'Eigene Dauer' = 'Custom duration'
    'min' = 'min'
    'Start' = 'Start'
    'Lyrics-Ordner öffnen' = 'Open lyrics folder'
    'Öffnet eine Datei, in die du die Lyrics mit Zeitangaben schreibst' = 'Opens a file where you write the lyrics with timestamps'
    'Desktop-Verknüpfung erstellen' = 'Create desktop shortcut'
    'Mit Icon in deiner Akzentfarbe' = 'With an icon in your accent color'
    'Programm-Ordner öffnen' = 'Open program folder'
    'Einstellungen exportieren' = 'Export settings'
    'Einstellungen importieren' = 'Import settings'
    'Schickt eine kurze Nachricht in die Chatbox' = 'Sends a short message to the chatbox'
    'Log leeren' = 'Clear log'
    'Macht lange Titel kürzer, damit mehr Platz für Lyrics und Status bleibt.' = 'Shortens long titles so there is more room for lyrics and status.'
    'Features ausblenden' = 'Hide features'
    '(feat. …) und (with …) aus dem Titel entfernen' = 'Remove (feat. …) and (with …) from the title'
    'Zusätze in Klammern ausblenden' = 'Hide extras in brackets'
    'z. B. (Remastered), [Live], - Radio Edit' = 'e.g. (Remastered), [Live], - Radio Edit'
    'Nur Hauptkünstler' = 'Main artist only'
    'Nur der erste Künstler statt aller Beteiligten' = 'Only the first artist instead of everyone involved'
    'Album ausblenden, wenn es wie der Song heißt' = 'Hide album if it has the same name as the song'
    'Bei Singles steht sonst zweimal dasselbe da' = 'Otherwise singles show the same name twice'
    'Aktualisieren alle' = 'Update every'
    'Beim Sprechen ausblenden' = 'Hide while talking'
    'Solange du redest, verschwindet die Chatbox' = 'The chatbox disappears while you talk'
    'Empfindlichkeit' = 'Sensitivity'
    'Niedrig' = 'Low'
    'Mittel' = 'Medium'
    'Hoch' = 'High'
    'Kein Mikrofon gefunden' = 'No microphone found'
    'Mikrofon' = 'Microphone'
    'du sprichst - Chatbox ausgeblendet' = 'you are talking - chatbox hidden'
    'Song-Zeile' = 'Song line'
    'Song-Icon' = 'Song icon'
    "$(C 0x1F3B5) Note" = "$(C 0x1F3B5) Note"
    "$(C 0x1F3A7) Kopfhörer" = "$(C 0x1F3A7) Headphones"
    "$(C 0x266A) Einfach" = "$(C 0x266A) Simple"
    'Keins' = 'None'
    'Künstler hochgestellt' = 'Superscript artist'
    'Titel ᵇʸ ᵏᵘⁿˢᵗˡᵉʳ' = 'Title ᵇʸ ᵃʳᵗⁱˢᵗ'
    'Kapitälchen-Schrift' = 'Small caps font'
    'ᴛɪᴛᴇʟ - ᴋüɴꜱᴛʟᴇʀ' = 'ᴛɪᴛʟᴇ - ᴀʀᴛɪꜱᴛ'
    'Album anzeigen' = 'Show album'
    'Restzeit statt Länge' = 'Remaining time instead of length'
    'Stil' = 'Style'
    'Länge' = 'Length'
    'Kurz' = 'Short'
    'Lang' = 'Long'
    'Layout' = 'Layout'
    'Trennzeichen' = 'Separator'
    'Leerzeile zwischen Song und Status' = 'Blank line between song and status'

    # Lyrics
    'Songtexte synchron zur Musik' = 'Lyrics synced to the music'
    'Live-Lyrics' = 'Live lyrics'
    'Aktuelle Zeile unten in der Chatbox' = 'Current line at the bottom of the chatbox'
    'Karaoke-Modus' = 'Karaoke mode'
    'Nur Song, aktuelle und nächste Zeile' = 'Only song, current and next line'
    'Titel ausblenden, wenn Lyrics laufen' = 'Hide title while lyrics are showing'
    'Nach 10 Sekunden nur noch die Lyrics' = 'Only lyrics after 10 seconds'
    'Kommen die Lyrics zu früh oder zu spät? Unter Erweitert > Lyrics-Timing einstellen.' = 'Lyrics too early or too late? Adjust under Advanced > Lyrics timing.'
    'Lyrics übersetzen' = 'Translate lyrics'
    'Zeigt die Übersetzung unter der Zeile' = 'Shows the translation below the line'
    'Sprache' = 'Language'
    'Deutsch' = 'German'
    'Englisch' = 'English'
    'Türkisch' = 'Turkish'
    'Spanisch' = 'Spanish'
    'Französisch' = 'French'
    'Russisch' = 'Russian'
    'Arabisch' = 'Arabic'
    'Polnisch' = 'Polish'
    'Koreanisch' = 'Korean'
    'Chinesisch' = 'Chinese'
    'Für Songs, zu denen keine Lyrics gefunden werden. Mit der Vorlage schreibst du sie selbst.' = 'For songs without lyrics. Use the template to write them yourself.'
    'Ordner öffnen' = 'Open folder'
    'Vorlage für aktuellen Song' = 'Template for current song'

    # Status
    'Uhrzeit & AFK' = 'Clock & AFK'
    'Auch per Tastenkürzel umschaltbar' = 'Can also be toggled with a hotkey'
    'Auto-AFK' = 'Auto-AFK'
    'Wenn Maus und Tastatur nicht benutzt werden (nur Desktop-Modus sinnvoll)' = 'When mouse and keyboard are not used (desktop mode only)'
    'Auto-AFK nach' = 'Auto-AFK after'
    'VRChat' = 'VRChat'
    'Spielzeit' = 'Play time'
    'Wie lange VRChat schon läuft' = 'How long VRChat has been running'
    'Welt und Spielerzahl' = 'World and player count'
    'Name der Welt und wie viele Leute da sind' = 'World name and how many people are there'
    'Eigener Text' = 'Custom text'
    'Mehrere Texte mit ; trennen, sie wechseln alle 10 Sekunden' = 'Separate multiple texts with ; they rotate every 10 seconds'

    'Künstler' = 'Artist'
    'Songs' = 'Songs'

    # Statistik
    '7 Tage' = '7 days'
    '30 Tage' = '30 days'
    'Gesamt' = 'All time'
    '7 Tage gehört' = 'Listened (7 days)'
    'Songs im Verlauf' = 'Songs in history'
    'Lieblings-Künstler' = 'Favorite artist'
    'Top-Songs' = 'Top songs'
    'Top-Künstler' = 'Top artists'
    'Zuletzt gehört' = 'Recently played'
    'Teilen' = 'Share'
    'Song kopieren' = 'Copy song'
    'Spotify-Link kopieren' = 'Copy Spotify link'
    'Verlauf öffnen' = 'Open history'
    'Noch keine Songs im Verlauf' = 'No songs in history yet'

    # Einstellungen
    'Aussehen' = 'Appearance'
    'Sprache der App' = 'App language'
    'Automatisch' = 'Automatic'
    'Das Panel startet nach dem Wechsel kurz neu' = 'The panel restarts briefly after changing'
    'Design' = 'Theme'
    'Dunkel' = 'Dark'
    'Hell' = 'Light'
    'Akzentfarbe' = 'Accent color'
    'Grün' = 'Green'
    'Rot' = 'Red'
    'Lila' = 'Purple'
    'Blau' = 'Blue'
    'Pink' = 'Pink'
    'Orange' = 'Orange'
    'Türkis' = 'Teal'
    'Gold' = 'Gold'
    'Panel immer im Vordergrund' = 'Panel always on top'
    'Musik-Quelle' = 'Music source'
    'Andere Musik-Apps erlauben' = 'Allow other music apps'
    'Wenn Spotify nicht läuft: Apple Music, Amazon Music, Deezer, YouTube Music usw. Normale YouTube-Videos werden ignoriert.' = 'When Spotify is not running: Apple Music, Amazon Music, Deezer, YouTube Music etc. Normal YouTube videos are ignored.'
    'Verhalten' = 'Behavior'
    'Mit Windows starten' = 'Start with Windows'
    'Benachrichtigung bei Songwechsel' = 'Notification on song change'
    'Song-Verlauf speichern' = 'Save song history'
    'Wird für die Statistik gebraucht' = 'Needed for statistics'
    'Programm' = 'Program'
    'Desktop-Verknüpfung' = 'Desktop shortcut'
    'Tool beenden' = 'Quit'
    "Fertig: Verknüpfung 'Spotify Chatbox' auf dem Desktop." = "Done: 'Spotify Chatbox' shortcut on the desktop."
    'Sichern & Zurücksetzen' = 'Backup & reset'
    'Exportieren' = 'Export'
    'Importieren' = 'Import'
    'Auf Standard zurücksetzen' = 'Reset to default'
    'Alle Einstellungen auf Standard zurücksetzen?' = 'Reset all settings to default?'
    'Zurücksetzen' = 'Reset'

    # Erweitert
    'Verbindung' = 'Connection'
    'Nur ändern, wenn VRChat auf einem anderen Gerät läuft (z. B. Quest über WLAN)' = 'Only change this if VRChat runs on another device (e.g. Quest over Wi-Fi)'
    'IP-Adresse' = 'IP address'
    'Standard: 127.0.0.1' = 'Default: 127.0.0.1'
    'Port' = 'Port'
    'Standard: 9000' = 'Default: 9000'
    'Verbindung testen' = 'Test connection'
    'Sende Testnachricht...' = 'Sending test message...'
    'Fehler' = 'Error'
    'Gesendet, aber VRChat läuft gerade nicht.' = 'Sent, but VRChat is not running right now.'
    'Gesendet, aber OSC ist in VRChat aus: Action Menu > Options > OSC > Enabled.' = 'Sent, but OSC is off in VRChat: Action Menu > Options > OSC > Enabled.'
    "Gesendet - in VRChat sollte jetzt 'Verbindung OK' über deinem Kopf stehen." = "Sent - 'Connection OK' should now show above your head in VRChat."
    'Lyrics-Timing' = 'Lyrics timing'
    'Versatz (wenn Lyrics zu früh/spät kommen)' = 'Offset (if lyrics are early/late)'
    'Plus = Lyrics kommen früher, Minus = später' = 'Plus = lyrics come earlier, minus = later'
    'Tastenkürzel' = 'Hotkeys'
    'Fehler-Log' = 'Error log'
    'Leeren' = 'Clear'
    'Keine Fehler' = 'No errors'
    'Chatbox an/aus' = 'Chatbox on/off'
    '15 min pausieren / weiter' = 'Pause 15 min / resume'
    'Play / Pause' = 'Play / Pause'
    'Nächster Song' = 'Next song'
    'Vorheriger Song' = 'Previous song'
    'AFK an/aus' = 'AFK on/off'
    'Strg+Alt+M' = 'Ctrl+Alt+M'
    'Strg+Alt+Shift+M' = 'Ctrl+Alt+Shift+M'
    'Strg+Alt+F9' = 'Ctrl+Alt+F9'
    'Strg+Alt+P' = 'Ctrl+Alt+P'
    'Strg+Alt+Shift+P' = 'Ctrl+Alt+Shift+P'
    'Strg+Alt+Pfeil hoch' = 'Ctrl+Alt+Up'
    'Strg+Alt+Pfeil rechts' = 'Ctrl+Alt+Right'
    'Strg+Alt+Pfeil links' = 'Ctrl+Alt+Left'
    'Strg+Alt+Pfeil runter' = 'Ctrl+Alt+Down'
    '(belegt)' = '(in use)'

    # Tray / Meldungen
    'Panel öffnen' = 'Open panel'
    'Chatbox anzeigen' = 'Show chatbox'
    'Pausieren' = 'Pause'
    'Beenden' = 'Quit'
    'Läuft gerade' = 'Now playing'
    'Chatbox eingeschaltet' = 'Chatbox turned on'
    'Chatbox ausgeschaltet' = 'Chatbox turned off'

    # Neu im iOS-Design
    'Inhalt' = 'Content'
    'Jeden Teil der Chatbox einzeln an- und ausschalten.' = 'Turn each part of the chatbox on or off.'
    'Künstler in eigener Zeile' = 'Artist on its own line'
    'Titel und Künstler stehen untereinander' = 'Title and artist are shown on separate lines'
    'VRChat zeigt nur einen minimalen Kasten' = 'VRChat only shows a minimal box'
    '1,5 s' = '1.5 s'
    '1,5 s ist das Schnellste, was VRChat erlaubt' = '1.5 s is the fastest VRChat allows'
    'Steht zwischen Titel und Künstler und zwischen den Teilen der Status-Zeile, z. B. Uhrzeit / Welt.' = 'Shown between title and artist and between the parts of the status line, e.g. clock / world.'
    'Leerzeile vor der Status-Zeile' = 'Blank line before the status line'
    'Zählt nur, wenn VRChat im Vordergrund ist. Redest du z. B. in Discord, bleibt die Chatbox stehen.' = 'Only counts while VRChat is in the foreground. If you talk in Discord, for example, the chatbox stays.'
    'Live-Ansicht' = 'Live view'
    'Klick auf eine Zeile springt im Song dorthin.' = 'Click a line to jump there in the song.'
    'Keine Lyrics für diesen Song' = 'No lyrics for this song'
    'Live-Lyrics sind aus' = 'Live lyrics are off'
    'Zeigt AFK in der Chatbox' = 'Shows AFK in the chatbox'
    'Mehrere Texte mit ; trennen, sie wechseln alle 10 Sekunden.' = 'Separate multiple texts with ; they rotate every 10 seconds.'
    'Diese Woche' = 'This week'
    'Die Chatbox verschwindet und kommt danach von selbst zurück.' = 'The chatbox disappears and comes back by itself afterwards.'
    'Minuten' = 'minutes'
    'Spieler in der Welt' = 'Players in world'
    'VRChat-Spielzeit' = 'VRChat play time'
    'VRChat aus' = 'VRChat off'
    'Lädt...' = 'Loading...'
    'Nur ändern, wenn VRChat auf einem anderen Gerät läuft (z. B. Quest über WLAN).' = 'Only change this if VRChat runs on another device (e.g. Quest over Wi-Fi).'
    'Plus = Lyrics kommen früher, Minus = später.' = 'Plus = lyrics come earlier, minus = later.'
    'Versatz' = 'Offset'
    'Verbindung, Lyrics-Timing und Fehler-Log' = 'Connection, lyrics timing and error log'
    # VRChat
    'Avatar-Größe und Speicherplatz' = 'Avatar size and storage'
    'Avatar-Größe' = 'Avatar size'
    'Geht über OSC von 1 cm bis 10 km, auch über die Grenzen vom Action-Menü hinaus. Manche Welten sperren die Größe.' = 'Works over OSC from 1 cm to 10 km, beyond the Action Menu limits. Some worlds lock the size.'
    'Augenhöhe' = 'Eye height'
    'So groß bist du in VRChat' = 'How tall you are in VRChat'
    'Außerhalb von 10 cm bis 100 m zeigt VRChat dir einen Warnhinweis an. Das ist normal.' = 'Outside 10 cm to 100 m VRChat shows you a warning. That is normal.'
    'Normal' = 'Normal'
    'Kleiner' = 'Smaller'
    'Größer' = 'Bigger'
    'Bitte schließe zuerst VRChat. Solange es läuft, sind die Dateien gesperrt.' = 'Please close VRChat first. The files are locked while it is running.'
    'Wird berechnet...' = 'Calculating...'
    'Wird gelöscht...' = 'Deleting...'
    'Avatare & Welten' = 'avatars & worlds'
    'auf' = 'on'
    'Einträge' = 'entries'
    'Nichts älter als 14 Tage' = 'Nothing older than 14 days'
    'Frei geworden:' = 'Freed:'
    'Cache zurück auf C: legen' = 'Move cache back to C:'
    'Cache auf Laufwerk D: verschieben' = 'Move cache to drive D:'
    'Gespeichert in' = 'Stored in'
    'Spart Platz auf C:. Avatare laden von D: etwas langsamer.' = 'Saves space on C:. Avatars load a bit slower from D:.'
    'Speicherplatz' = 'Storage'
    'VRChat speichert jeden Avatar und jede Welt, die du gesehen hast. Gelöschtes lädt VRChat beim nächsten Mal einfach neu herunter.' = 'VRChat stores every avatar and world you have seen. Deleted items are simply downloaded again next time.'
    'VRChat-Cache' = 'VRChat cache'
    'Alte Avatare & Welten löschen' = 'Delete old avatars & worlds'
    'Ganzen Cache löschen' = 'Delete entire cache'
    'Alle gespeicherten Avatare und Welten löschen? VRChat lädt sie bei Bedarf neu herunter.' = 'Delete all stored avatars and worlds? VRChat downloads them again when needed.'
    'Cache löschen' = 'Delete cache'
    'Cache-Ort' = 'Cache location'
    'VRChat muss dafür geschlossen sein. Der alte Cache wird dabei gelöscht, damit er keinen Platz mehr belegt.' = 'VRChat must be closed for this. The old cache is deleted so it no longer takes up space.'
    'Laufwerk D: wurde nicht gefunden.' = 'Drive D: was not found.'
    'Speicherort ändern? Der alte Cache wird gelöscht und VRChat lädt Avatare und Welten am neuen Ort neu herunter.' = 'Change location? The old cache is deleted and VRChat downloads avatars and worlds again at the new location.'
    'Cache-Ordner öffnen' = 'Open cache folder'
    'Chatbox pausieren' = 'Pause chatbox'
    'Eigene Größe' = 'Custom size'
    'z. B. 1,75 m, 30 cm oder 2 km' = 'e.g. 1.75 m, 30 cm or 2 km'
    'Setzen' = 'Set'
    'Zeitraum' = 'Time range'
    '3 Tage' = '3 days'
    '14 Tage' = '14 days'
    'Wann du einen Avatar oder eine Welt zuletzt gesehen hast' = 'When you last saw an avatar or world'
    'Älter als {0} Tage löschen' = 'Delete older than {0} days'
    'Neuer als {0} Tage löschen' = 'Delete newer than {0} days'
    'Älter als 14 Tage löschen' = 'Delete older than 14 days'
    'Neuer als 14 Tage löschen' = 'Delete newer than 14 days'
    'lange nicht gesehen' = 'not seen for a while'
    'kürzlich gesehen' = 'seen recently'
    'Nichts gefunden' = 'Nothing found'
    'Kleines Fenster unten rechts, in VR über XSOverlay' = 'Small window at the bottom right, in VR via XSOverlay'
    'Musik im Mic' = 'Music in mic'
    'Andere in VRChat hören deinen Song' = 'Others in VRChat hear your song'
    'Spotify hörst du selbst ganz normal weiter. VRChat-Sounds und andere Spieler kommen nicht mit ins Mikrofon, nur Spotify.' = 'You keep hearing Spotify as usual. VRChat sounds and other players do not go into the mic, only Spotify.'
    'Song über dein Mikrofon abspielen' = 'Play the song through your mic'
    'Deine Stimme' = 'Your voice'
    'Das hören die anderen' = 'What others hear'
    'Lautstärke' = 'Volume'
    'Angleichen macht leise Songs lauter und laute leiser. So bleibt es für andere gleich laut, auch wenn du Spotify selbst leiser stellst.' = 'Even out makes quiet songs louder and loud ones quieter. It stays equally loud for others, even if you turn Spotify down for yourself.'
    'Musik' = 'Music'
    'Stimme' = 'Voice'
    'Lautstärke angleichen' = 'Even out volume'
    'Jeder Song kommt gleich laut an' = 'Every song arrives equally loud'
    'Musik leiser, wenn du sprichst' = 'Lower music while you talk'
    'Damit man dich immer versteht' = 'So people can always understand you'
    'Stimme mitschicken' = 'Send your voice too'
    'Aus = nur Musik, du bist dann stumm' = 'Off = music only, you are muted'
    'Geräte' = 'Devices'
    'Dein Mikrofon' = 'Your microphone'
    'Windows-Standard' = 'Windows default'
    'Virtuelles Kabel' = 'Virtual cable'
    'Automatisch finden' = 'Find automatically'
    'Einrichtung (einmalig)' = 'Setup (one time)'
    'Am Ende hört VRChat auf das Kabel und das Tool mischt dort Musik und Stimme zusammen.' = 'VRChat then listens to the cable and the tool mixes music and voice into it.'
    '1. VB-CABLE installieren' = '1. Install VB-CABLE'
    'Kostenloses virtuelles Mikrofon. Danach PC neu starten.' = 'Free virtual microphone. Restart your PC afterwards.'
    '2. In VRChat als Mikrofon wählen' = '2. Select it as microphone in VRChat'
    'Einstellungen > Audio > Mikrofon: CABLE Output' = 'Settings > Audio > Microphone: CABLE Output'
    '3. Rauschunterdrückung aus' = '3. Turn off noise suppression'
    'In VRChat bei Audio > Mikrofon. Sonst filtert VRChat die Musik weg.' = 'In VRChat under Audio > Microphone. Otherwise VRChat filters out the music.'
    'Windows-Soundeinstellungen' = 'Windows sound settings'
    'Kein virtuelles Kabel gefunden, siehe Einrichtung' = 'No virtual cable found, see setup'
    'Läuft' = 'Running'
    'Wartet auf Spotify' = 'Waiting for Spotify'
    'Startet...' = 'Starting...'
    'Die Audio-Engine konnte nicht geladen werden (MusicMic.cs fehlt?).' = 'The audio engine could not be loaded (MusicMic.cs missing?).'
    'Kabel' = 'Cable'
    'Rauschsperre' = 'Noise gate'
    'Mikro offen' = 'Mic open'
    'Mikro stumm (Rauschsperre)' = 'Mic muted (noise gate)'
    'Rauschsperre: Dein Mikro ist stumm, solange du nicht sprichst. Rauscht es noch, höher stellen. Werden Wörter abgeschnitten, niedriger. 0 = aus.' = 'Noise gate: your mic is muted while you are not talking. Still noisy? Turn it up. Words cut off? Turn it down. 0 = off.'
}

# Sprache festlegen: "auto" = Deutsch auf deutschem Windows, sonst Englisch
function Resolve-Language([string]$setting) {
    if ($setting -in 'de', 'en') { return $setting }
    if ([Globalization.CultureInfo]::CurrentUICulture.TwoLetterISOLanguageName -eq 'de') { 'de' } else { 'en' }
}

function T([string]$s) {
    if ($script:lang -eq 'de' -or -not $s) { return $s }
    $e = $texts[$s]
    if ($e) { $e } else { $s }
}

function Format-Duration([double]$sec) {
    $ts = [TimeSpan]::FromSeconds($sec)
    $h = [int][Math]::Floor($ts.TotalHours); $m = if ($h) { $ts.Minutes } else { [int]$ts.TotalMinutes }
    if ($h) { "$h h $m min" } else { "$m min" }
}

# Anzahl in Listen ("3x")
function Format-Count([int]$n) { "${n}x" }
